/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.laundry;

import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luviana
 */
public class form_main extends javax.swing.JFrame {

    /**
     * Creates new form form_main
     */
    public form_main(String admin) {
        initComponents();
        setAdmin(admin);
    }
    
    public form_main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnSegarkan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtHarga1 = new javax.swing.JTextField();
        txtKode = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtTelp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtBrg5 = new javax.swing.JTextField();
        txtBrg1 = new javax.swing.JTextField();
        txtBrg2 = new javax.swing.JTextField();
        txtBrg3 = new javax.swing.JTextField();
        txtBrg4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        cbJenis = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        rbTidak = new javax.swing.JRadioButton();
        rbIya = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        txtHarga2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnBersihkan = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        btnHitungTotal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        txtCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(txtCari);
        txtCari.setBounds(770, 20, 170, 30);

        btnCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel2.add(btnCari);
        btnCari.setBounds(950, 20, 81, 30);

        btnCetak.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        jPanel2.add(btnCetak);
        btnCetak.setBounds(250, 20, 100, 30);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 102));

        Table1.setBackground(new java.awt.Color(255, 255, 102));
        Table1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kd Transaksi", "Nama", "No. Telepon", "Alamat", "Pakaian", "Sepatu, Tas", "Sprei, Selimut", "Karpet", "Dll", "Jenis Laundry", "Antar-Jemput", "Total Harga"
            }
        ));
        jScrollPane1.setViewportView(Table1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 1040, 320);

        btnHapus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnHapus);
        btnHapus.setBounds(10, 20, 100, 30);

        btnSegarkan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSegarkan.setText("Segarkan");
        btnSegarkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSegarkanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSegarkan);
        btnSegarkan.setBounds(130, 20, 100, 30);

        jTabbedPane1.addTab("Data Pelanggan Laundry", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Kode Transaksi");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 11, 110, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Data Pelanggan");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 47, 250, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Total Pembayaran");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(610, 230, 250, 25);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 78, 250, 10);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nomor Telepon");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 160, 250, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Alamat");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 230, 250, 25);

        txtHarga1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtHarga1);
        txtHarga1.setBounds(310, 350, 170, 30);

        txtKode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtKode);
        txtKode.setBounds(130, 10, 120, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Data Barang");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(310, 50, 250, 25);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(310, 80, 250, 10);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Data Layanan");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(610, 50, 250, 25);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(610, 80, 250, 10);

        txtTelp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtTelp);
        txtTelp.setBounds(10, 190, 250, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Nama");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 90, 250, 25);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("5. Dll");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(310, 280, 110, 25);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("kg   x  Rp. 8000,-");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(470, 280, 100, 25);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("2. Sepatu, Tas");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(310, 160, 110, 25);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("3. Sprei, Selimut");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(310, 200, 110, 25);

        txtNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtNama);
        txtNama.setBounds(10, 120, 250, 30);

        txtBrg5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtBrg5);
        txtBrg5.setBounds(420, 280, 40, 25);

        txtBrg1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtBrg1);
        txtBrg1.setBounds(420, 120, 40, 25);

        txtBrg2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtBrg2);
        txtBrg2.setBounds(420, 160, 40, 25);

        txtBrg3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtBrg3);
        txtBrg3.setBounds(420, 200, 40, 25);

        txtBrg4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtBrg4);
        txtBrg4.setBounds(420, 240, 40, 25);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("1. Pakaian");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(310, 120, 110, 25);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("kg   x  Rp. 5000,-");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(470, 120, 100, 25);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("kg   x  Rp. 6000,-");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(470, 160, 100, 25);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("kg   x  Rp. 7000,-");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(470, 200, 100, 25);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("kg   x  Rp. 8000,-");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(470, 240, 100, 25);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Jenis Barang");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(310, 90, 250, 25);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Total Harga");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(310, 320, 260, 25);

        txtAlamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtAlamat);
        txtAlamat.setBounds(10, 260, 250, 30);

        cbJenis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuci Kering", "Setrika", "Cuci Kering + Setrika" }));
        jPanel1.add(cbJenis);
        cbJenis.setBounds(610, 120, 250, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Jenis Laundry");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(610, 90, 250, 25);

        rbTidak.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbTidak);
        rbTidak.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbTidak.setText("Tidak");
        jPanel1.add(rbTidak);
        rbTidak.setBounds(720, 190, 103, 30);

        rbIya.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbIya);
        rbIya.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbIya.setText("Iya");
        jPanel1.add(rbIya);
        rbIya.setBounds(610, 190, 103, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Jasa Antar - Jemput");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(610, 160, 250, 25);

        txtHarga2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtHarga2);
        txtHarga2.setBounds(610, 260, 170, 30);

        jPanel5.setBackground(new java.awt.Color(255, 255, 102));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 51), 2, true));

        btnBersihkan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBersihkan.setText("Bersihkan");
        btnBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihkanActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(920, 110, 120, 110);

        btnHitung.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        jPanel1.add(btnHitung);
        btnHitung.setBounds(490, 350, 81, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("4. Karpet");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(310, 240, 110, 25);

        btnHitungTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHitungTotal.setText("Hitung");
        btnHitungTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungTotalActionPerformed(evt);
            }
        });
        jPanel1.add(btnHitungTotal);
        btnHitungTotal.setBounds(790, 260, 81, 30);

        jTabbedPane1.addTab("Input Data", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 110, 1070, 420);

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 97, 1060, 5);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 26)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/laundry/logo5.png"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(5, 1, 340, 100);

        lblAdmin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(lblAdmin);
        lblAdmin.setBounds(830, 50, 130, 30);

        lblTanggal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(lblTanggal);
        lblTanggal.setBounds(830, 20, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Admin    :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(770, 50, 60, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tanggal  :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(770, 20, 60, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1060, 550);

        setBounds(0, 0, 1075, 587);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungTotalActionPerformed
        // TODO add your handling code here:

        int harga1 = Integer.parseInt(txtHarga1.getText());
        int jenis = 0;
        if(cbJenis.getSelectedItem().equals("Cuci Kering")){
            jenis = jenis + 4000;
        } else if(cbJenis.getSelectedItem().equals("Setrika"))
        {
            jenis = jenis + 4000;
        } else if(cbJenis.getSelectedItem().equals("Cuci Kering + Setrika"))
        {
            jenis = jenis + 5000;
        }
        int harga2 = harga1 + jenis;
        int harga3 = harga2;
        String antar_jemput = "";
        if (rbIya.isSelected()){
            antar_jemput = "Y";
            harga3 = harga2 + 5000;
        } else {
            antar_jemput = "T";
        }
        txtHarga2.setText(Integer.toString(harga3));
    }//GEN-LAST:event_btnHitungTotalActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        int pakaian = Integer.parseInt(txtBrg1.getText());
        pakaian = pakaian * 5000;
        int spt_tas = Integer.parseInt(txtBrg2.getText());
        spt_tas = spt_tas * 6000;
        int sprei_slmt = Integer.parseInt(txtBrg3.getText());
        sprei_slmt = sprei_slmt * 7000;
        int karpet = Integer.parseInt(txtBrg4.getText());
        karpet = karpet * 8000;
        int dll = Integer.parseInt(txtBrg5.getText());
        dll = dll * 8000;
        int total = pakaian + spt_tas + sprei_slmt + karpet + dll;
        txtHarga1.setText(Integer.toString(total));
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        
        int pakaian = Integer.parseInt(txtBrg1.getText());
        int spt_tas = Integer.parseInt(txtBrg2.getText());
        int sprei_slmt = Integer.parseInt(txtBrg3.getText());
        int karpet = Integer.parseInt(txtBrg4.getText());
        int dll = Integer.parseInt(txtBrg5.getText());
        String antar_jemput = "";
        if (rbIya.isSelected()) {
            antar_jemput = "Y";
        } else {
            antar_jemput = "T";
        }
        String jns_laundry = "";
        if(cbJenis.getSelectedItem().equals("Cuci Kering")){
            jns_laundry = "Cuci Kering";
        } else if(cbJenis.getSelectedItem().equals("Setrika"))
        {
            jns_laundry = "Setrika";
        } else if(cbJenis.getSelectedItem().equals("Cuci Kering + Setrika"))
        {
            jns_laundry = "Cuci Kering + Setrika";
        }
        
        if(txtNama.getText().equals("") || txtTelp.getText().equals("") || txtAlamat.getText().equals("") ||
                txtBrg1.getText().equals("") || txtBrg2.getText().equals("") || txtBrg3.getText().equals("") ||
                txtBrg4.getText().equals("") || txtBrg5.getText().equals("") || txtHarga1.getText().equals("") ||
                txtHarga2.getText().equals("") || txtKode.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } 
        else {
        String SQL = "INSERT INTO tb_pesanan(kd_transaksi, nama_plg, telp, alamat, pakaian, spt_tas, sprei_slmt, karpet, dll, jns_laundry, antar_jemput, total_bayar)"
                + " VALUES ('" + txtKode.getText() + "','" + txtNama.getText() + "','" + txtTelp + "','" + txtAlamat.getText() + "',"
                + pakaian + "," + spt_tas +  "," + sprei_slmt +  "," + karpet +  "," + dll +  ",'" + jns_laundry + "','" + 
                antar_jemput + ",'" + txtHarga2.getText() + "')";
        int status = KoneksiDB.execute(SQL);
        if(status==1) {
            JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            try {
                selectData();
            } catch (SQLException ex) {
                Logger.getLogger(form_main.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
        }
      }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihkanActionPerformed
        // TODO add your handling code here:
        
        txtKode.setText("");
        txtNama.setText("");
        txtTelp.setText("");
        txtAlamat.setText("");
        txtBrg1.setText("");
        txtBrg2.setText("");
        txtBrg3.setText("");
        txtBrg4.setText("");
        txtBrg5.setText("");
        txtHarga1.setText("");
        txtHarga2.setText("");
        buttonGroup1.clearSelection();
        cbJenis.setSelectedItem(null);
    }//GEN-LAST:event_btnBersihkanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        
        int baris = Table1.getSelectedRow();
        if (baris != -1) {
            String kd_transaksi = Table1.getValueAt(baris, 1).toString();
            String SQL = "DELETE FROM tb_pesanan WHERE kd_transaksi = '" + kd_transaksi + "'";
            int status = 0;
            status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSegarkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegarkanActionPerformed
        // TODO add your handling code here:
        
        try {
            selectData();
        } catch (SQLException ex) {
            Logger.getLogger(form_main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSegarkanActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        
        MessageFormat header = new MessageFormat("Data Laundry Mentari");
        MessageFormat footer = new MessageFormat("Pgae (0,number,integer)");
        try {
            Table1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (PrinterException ex) {
            Logger.getLogger(form_main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HeadlessException ex) {
            Logger.getLogger(form_main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        
        try{
            String konString = "jdbc:mysql://localhost:3306/db_laundry"; 
            Connection conn;
            conn = (com.mysql.jdbc.Connection) 
            DriverManager.getConnection(konString,"root","");
            
            Statement st = conn.createStatement();
            String search = txtCari.getText();
            ResultSet rs = st.executeQuery("SELECT * FROM tb_pesanan WHERE nama_plg like '%"+ search +"%' OR kd_transaksi like '%"+ search + "%'");
            DefaultTableModel dtm = (DefaultTableModel) Table1.getModel();

            dtm.setRowCount(0);
            String [] data = new String[12];
            int i = 1;

            while(rs.next())
            {
                data[0] = rs.getString("kd_transaksi");
                data[1] = rs.getString("nama_plg");
                data[2] = rs.getString("telp");
                data[3] = rs.getString("alamat");
                data[4] = rs.getString("pakaian");
                data[5] = rs.getString("spt_tas");
                data[6] = rs.getString("sprei_slmt");
                data[7] = rs.getString("karpet");
                data[8] = rs.getString("dll");
                data[9] = rs.getString("jns_laundry");
                data[10] = rs.getString("antar_jemput");
                data[11] = rs.getString("total_bayar");
                dtm.addRow(data);
                i++;
            }
            rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Data yang Anda cari Tidak dapat Ditemukan");
            System.err.println("error (search) : " +ex);
        }
    }//GEN-LAST:event_btnCariActionPerformed

    public void selectData() throws SQLException {
        String kolom[] = {"kd_transaksi", "nama_plg", "telp", "alamat", "pakaian", "spt_tas", "sprei_slmt", "karpet", "dll", "jns_laundry", "antar_jemput", "total_bayar"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_pesanan";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()) {
                String kd_transaksi = rs.getString(1);
                String nama_plg = rs.getString(2);
                String telp = rs.getString(3);
                String alamat = rs.getString(4);
                String pakaian = rs.getString(5);
                String spt_tas = rs.getString(6);
                String sprei_slmt = rs.getString(7);
                String karpet = rs.getString(8);
                String dll = rs.getString(9);
                String jns_laundry = rs.getString(10);
                String antar_jemput = rs.getString(11);
                String total_bayar = rs.getString(12);
                String data[] = {kd_transaksi, nama_plg, telp, alamat, pakaian, spt_tas, sprei_slmt, karpet, dll, jns_laundry, antar_jemput, total_bayar};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(form_main.class.getName()).log(Level.SEVERE, null, ex);
        }
        Table1.setModel(dtm);
    }
    
    private void setAdmin(String admin) {
        lblAdmin.setText(admin);
    }
    
    public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
        lblTanggal.setText(kal.format(skrg));
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JButton btnBersihkan;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnHitungTotal;
    private javax.swing.JButton btnSegarkan;
    private javax.swing.JButton btnSimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JRadioButton rbIya;
    private javax.swing.JRadioButton rbTidak;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtBrg1;
    private javax.swing.JTextField txtBrg2;
    private javax.swing.JTextField txtBrg3;
    private javax.swing.JTextField txtBrg4;
    private javax.swing.JTextField txtBrg5;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHarga1;
    private javax.swing.JTextField txtHarga2;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelp;
    // End of variables declaration//GEN-END:variables

}
